### ISSUE TITLE
Add support for `Deno.env`

### ISSUE THREAD

**Issue by dancrumb** [garronej/denoify#103]
Calls to `process.env` should be relatively straightforward to transpile... at the very least, a `process.env.XYZ` => `Deno.env('XYZ')` mapping would help.

I'm happy to attempt a PR, once I get to know the codebase better

**Comment by garronej** [comment]
Absolutely. Thank  you for pointing that out.  

You're PR will be very much wellcomed!  

You'd have to work on this file:  https://github.com/garronej/denoify/blob/main/src/lib/denoifySingleFile.ts  

And update this test file: https://github.com/garronej/denoify/blob/main/test/denoifySingleFile.test.ts
