### ISSUE TITLE
Open Source Software Stack for 3G

### ISSUE THREAD

**Issue by serttasbugrahan** [garronej/denoify#120]
Hello, I am a student at Kocaeli University. I am looking for open source software stack for 3G like OpenAirInterface for 5G or Osmocom for 2G for my work. (Osmocom has partial support for 3G)

I request you to direct me to the right resource that may know.

Thanks for your time and interest.

Kind regards,

**Comment by garronej** [comment]
I answered as best as I could here: https://github.com/garronej/gsm-modem-connection/issues/6
