### ISSUE TITLE
`'C:\Program' is not recognized as an internal or external command`

### ISSUE THREAD

**Issue by wojpawlik** [garronej/denoify#13]
```
$ npx denoify
C:\Users\Wojciech\AppData\Roaming\npm-cache\_npx\3560\node_modules\denoify\bin\denoify.js:6
process.once("unhandledRejection", error => { throw error; });
                                              ^

Error: Command failed: C:\Program Files\nodejs\node.exe C:\Users\Wojciech\AppData\Roaming\npm-cache\_npx\3560\node_modules\denoify\bin\replacer\index.js "import { Buffer } from \"buffer\"" 0.0.0 "deno_lib\\core\\network"
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Program Files\\nodejs\\node.exe C:\\Users\\Wojciech\\AppData\\Roaming\\npm-cache\\_npx\\3560\\node_modules\\denoify\\bin\\replacer\\index.js "import { Buffer } from \\"buffer\\"" 0.0.0 "deno_lib\\\\core\\\\network"',
  stderr: "'C:\\Program' is not recognized as an internal or external command,\r\n" +
    'operable program or batch file.\r\n'
}
```

I believe the reason is creating a shell command by naive string concatenation: https://github.com/garronej/denoify/blob/a81800d634936f2214481f2d6888661494834e41/src/lib/replacer.ts#L103-L106

**Comment by garronej** [comment]
Damn it,  
I know this was bound to happen. I didn't run the test on windows for a while.  
I definitely need to setup a CI job for it.  

I will fix it tomorrow if I can spare some time.  

Thanks for reporting

**Comment by garronej** [comment]
@wojpawlik sorry, I haven't been able to do it yet but I am on it.

**Comment by garronej** [comment]
@wojpawlik It took me longer to setup a windows environement than actually fixing the bug...
Do not hesitate to reopen if the problem presists. 

Cheers

**Comment by wojpawlik** [comment]
Thanks, it works now, I mean, it prompts me to denoify my dependencies :) How would one go about denofiying https://github.com/KnorpelSenf/typegram, which is 100% types, no JS?

**Comment by garronej** [comment]
I am at work now so I can't do it now but it would help me if you share examples where you import typegram in your code. Even beter would be if you showed me the repo you are working on.

**Comment by wojpawlik** [comment]
I'm working on https://github.com/telegraf/telegraf.

**Comment by garronej** [comment]
Cool! This is a big project. I will try to help you Denoify it.

**Comment by garronej** [comment]
I can't now but I will try to have a look tonight

**Comment by garronej** [comment]
Hey @wojpawlik, I am sorry but telegraf uses `http` and `https` node builtin. That are [not yet supported](https://deno.land/std@0.68.0/node#supported-builtins). If you are really serious about supporting Deno it is still possible to make telegraf portable but it will involve writing wrappers around the unsupported node builtins and coming out wit custom Deno implementation for those wrappers.  
I can assist you but I can't do it for you as it require heavy refactoring. 
You can also wait for the node builtin support to get better... 

Sorry about that, the tool will get better with time...

**Comment by wojpawlik** [comment]
Thanks. I'm not that determined right now, I'll wait for `https?` support.

**Comment by garronej** [comment]
@wojpawlik Allright, I will ping you when the deno's node compatibility layer is completed enough to support `telgraf`, unfortunately, it does not seems to be the Deno's team priority right now so it make take some time.
