### ISSUE TITLE
README.md moved to deno_dist as subdirectory

### ISSUE THREAD

**Issue by gensior** [garronej/denoify#16]
I had been using v0.2.22 just fine on a project that I started a few months ago. I just upgraded to v0.5.5 and now when I run `denoify` I get an error that a subdirectory could not be removed.

Turns out denoify is copying my readme.md file as a directory within the deno_dist folder, rather than a file.

I'm running this on Windows 10.

**Comment by garronej** [comment]
Ok sorry about that. :/
Could you give me the link of the project you are working on (if it is opensource).
I will try to get it fix today.

**Comment by gensior** [comment]
No worries, I was able to keep using the original version for now. 

Here’s my [project](https://gitlab.com/jewel-duel/domain)

**Comment by garronej** [comment]
Cool to see some game dev happening within the Deno ecosystem. 
I will get it fixed this weekend, I'll tell you when it's done. 
Thank you for reporting!

**Comment by garronej** [comment]
@gensior fixed, thank you for reporting

**Comment by gensior** [comment]
Sorry for the late reply, I finally had time to check. It works like a charm, thank you!
