### ISSUE TITLE
How to exclude a folder from copying over to /deno_dist?

### ISSUE THREAD

**Issue by yandeu** [garronej/denoify#21]
Hi @garronej,

I took a look at the [package.json settings](https://github.com/garronej/my_dummy_npm_and_deno_module/blob/5cbf9ad914a4632491fd64615a84f450bb24a9ae/package.json#L19) but I could not exclude an entire folder from being copied over to `deno_dist`.

In my [project](https://github.com/nanojsx/nano), I would like to exclude the folders `/src/bundles` and `/src/dev` from getting copied over to `/deno_dist`.  
Is it possible to configure this with denoify? Or should I use another approach instead?

Thanks :)

**Comment by garronej** [comment]
Hi @yandeu, I am only seeing your issue now, let me have a look...

**Comment by garronej** [comment]
I understand the usecase. Unfortunately, as for now, there is no way to exclude a whole  parent directory of `src/` from being transpiled by Denoify.  
You can, however, add [`// @denoify-ignore`](https://github.com/garronej/my_dummy_npm_and_deno_module/blob/da1a5ab4d0e61a61b559c64ba6ed26422ceaa405/src/bin/customReplacer.ts) at the top of the files you dont want to be copied over `deno_dist`... 
But maybe it's not an ideal solution is it?

**Comment by yandeu** [comment]
Thanks! I thought I just keep entering the wrong settings.

---

No, I just use `rimraf` then :smiley: 

```json
"scripts": {
  "denoify": "rimraf deno_lib && denoify && rimraf deno_lib/bundles deno_lib/dev"
}
```
