### ISSUE TITLE
Does not work with yarn workspaces

### ISSUE THREAD

**Issue by hayes** [garronej/denoify#23]
Currently denoify does not work well with packages inside yarn workspaces because modules are mostly hoisted into the root node_modules directory.

`getInstalledVersionPackageJsonFactory` can't find these packages when they are hoisted.

One way to fix this would be to use require.resolve instead by doing something like:

```js
return require.resolve(nodeModuleName, {paths: [projectPath]}).replace(/^(.*\/node_modules\/[^/]*).*/, '$1');
```

insttead of
```js
return st.find_module_path(nodeModuleName, projectPath);
```

**Comment by garronej** [comment]
Fantastic investigation
