### ISSUE TITLE
Dead link in the README

### ISSUE THREAD

**Issue by andreswebs** [garronej/denoify#27]
Hi,

this link in the [README](https://github.com/garronej/denoify#what-it-is):

<https://github.com/denoland/deno/tree/master/std/node/#commonjs-module-loading>

is dead, and could be updated to:

<https://github.com/denoland/deno_std/tree/main/node#commonjs-module-loading>

I can open a PR, let me know if it helps.

**Comment by garronej** [comment]
Hi,  
Thank you for letting me know.  
Yes please open a PR, I am always happy to have a new contributor in the list :)
