### ISSUE TITLE
How to denoify a ECMAScript modules package?

### ISSUE THREAD

**Issue by yandeu** [garronej/denoify#29]
Hi

I'm trying to denoify a package that outputs only ESM code. But when I denoify it, the output is:
```ts
import { hello } from './feature.js/index.ts'
```
instead of
```ts
import { hello } from './feature.ts'
```

Any idea what I should change? Here is [my repsitory](https://github.com/yandeu/denoify-esm).

Thanks a lot!

**Comment by garronej** [comment]
Hi @yandeu,  
I will have a look if there is something easy I can do about it but currently Denoify only works with TypeScript codebase.

**Comment by yandeu** [comment]
Hi @garronej,

Thanks for looking at it. It actually is a TypeScript codebase. 

It should run on Deno and Node.js (esm-only).

The repo is pretty small. I guess you will immediately understand the issue.
