### ISSUE TITLE
Built-in module auto porting

### ISSUE THREAD

**Issue by Artrix9095** [garronej/denoify#39]
I have a scenario. So, lets say your using node-fetch for your NodeJS version of your library, but you want to use the built-in fetch module in deno. Or lets say you use ws for nodejs and the built-in websocket module in deno. I currently have a very hacky solution 
```ts
const isDeno = () => {
    // @ts-ignore
    try {
        window.fetch; 
        return true
    } catch { return false }
}
// @ts-ignore
const WebSocket = isDeno() ? window.WebSocket : require('ws')


...
```
Cons of this method is... I no longer get intellisense for the `WebSocket` variable.

I think something like this would be nice in ports
```json
{
    "ports": {
        "ws": "builtins://WebSocket"
    }
}
```

IF this is possible this would be a huge help to me and my team.

Thanks!

**Comment by garronej** [comment]
Hi @Artrix9095,  

Thanks for reaching out.  I think there is something in Denoify already that will fit your needs.  
Do you know about the `.deno.ts` files?  

In [my_dummy_npm_and_deno_module](https://github.com/garronej/my_dummy_npm_and_deno_module#step-2-enabling-the-modules-hard-dependencies-to-run-on-deno)
![image](https://user-images.githubusercontent.com/6702424/153190780-5e6917ec-48bf-46eb-9570-d5ef1ca983a1.png)

- [hash.ts](https://github.com/garronej/denoify/tree/master/src/lib/hash.ts)  
- [hash.deno.ts](https://github.com/garronej/denoify/tree/master/src/lib/hash.deno.ts)  

In your cas you could have a file for node:  
`tools/WebSocket.ts`
```ts
import WebSocket from 'ws';
export { WebSocket };
```
And a file for deno
`tools/WebSocket.deno.ts`
```ts
export const { WebSocket } = window;
```

And then whenever you need `WebSocket` import it just like:  

```ts
import { WebSocket } from "../tools/WebSocket";
```

If you are running on Deno it will import `WebSocket.deno.ts`, on node it will be `WebSocket.ts`

Hopes it fit your needs.  

Best regards,

**Comment by Artrix9095** [comment]
Thanks for the fast reply, this should work. Thanks!
