### ISSUE TITLE
Custom replacers should be passed the file path of the file the import was in

### ISSUE THREAD

**Issue by RebeccaStevens** [garronej/denoify#42]
There doesn't seem to be any way to get the path of the file being worked on with in a custom replacer. Thus it makes it impossible to return a relative path for the import.

```ts
await makeThisModuleAnExecutableReplacer(
  ({ importExportStatement, parsedImportExportStatement, destDirPath }) => {
    const absolutePath = customAbsolutePathResolver(parsedImportExportStatement);
    const relativePath = path.relative("???????", absolutePath);
    const relativeImport = createImportString(parsedImportExportStatement, relativePath);
    return Promise.resolve(relativeImport);
  }
);
```

**Comment by garronej** [comment]
@RebeccaStevens First of all, I acknowledge that custom replacers are hard to apprehend.  

Now isn't what you are looking for `destDirPath` ?!  

Consider this example of custom replacer:  

It takes:  
[`src/lib/Cat.ts`](https://github.com/garronej/my_dummy_npm_and_deno_module/blob/55cfa4f0a86be555c910631b9fa7c85a44f5e5a0/src/lib/Cat.ts#L10)
```typescript
import * as lp from "left-pad";
```
And transforms it into:  
[`deno_dist/lib/Cat.ts`](https://github.com/garronej/my_dummy_npm_and_deno_module/blob/55cfa4f0a86be555c910631b9fa7c85a44f5e5a0/deno_dist/lib/Cat.ts#L10)  
```typescript
import { leftPad as lp } from "../tools/leftPad.ts";
```

The import is made relative to where `Cat.ts` is relative to the `tools` directory. I think that's what you are trying to achieve.  

[This is the code of the replacer](https://github.com/garronej/my_dummy_npm_and_deno_module/blob/55cfa4f0a86be555c910631b9fa7c85a44f5e5a0/src/bin/customReplacer.ts#L35-L38), as you can see, it is calling `path.relative()`.  

Let me know if it helps.  

PS: Just in case you would have missed it, there is [this demo repo](https://github.com/garronej/my_dummy_npm_and_deno_module) where I try to put in practice the different ways to circumvent the denoify limitations.

**Comment by RebeccaStevens** [comment]
Yeah, that makes sense. Not sure why I didn't realize I could just replace the "deno_dest" part of the path `destDirPath` with my "src" path. Guess I was just too tired.
