### ISSUE TITLE
fix(typo): typo in help of argument message

### ISSUE THREAD

**Issue by GervinFung** [garronej/denoify#45]
Hi, I believe it is a typo right [here](https://github.com/garronej/denoify/blob/f9959d457b90093f7bdf113e7944791bf0c1e5e6/src/lib/denoify.ts#L314), instead it should be `package.json`. Would a PR for this be welcomed?

**Comment by garronej** [comment]
Yes vert wellcome ☺️

**Comment by GervinFung** [comment]
> Yes very wellcome relaxed

A PR was made, see [here](#46)
