### ISSUE TITLE
chore(format): setup prettier for more consistent formatting

### ISSUE THREAD

**Issue by GervinFung** [garronej/denoify#48]
Hey sir, the last time I cloned this repository I have to open `vim` to edit instead of `neovim` to edit it because my `neovim` was setup to auto format on save, which caused a lot of unnecessary changes as my formatting is setup differently. I believe that you have this feature enabled in your `vscode` as well as I see that you added `.vscode` to gitignore.

I think this project should have a `.prettierrc` file to provide a consistent formatting for all contributors to reduce unnecessary changes due to inconsistent formatting. If you are ok with it, I will make a PR for it and maybe we can discuss about the formatting, like which style do you prefer, etc.

**Comment by garronej** [comment]
Hi @GervinFung,  

Thanks for the proposal!  
Yes, I would gladly accept your PR.  
If you could configure it in a way that reduces the diff with the current state of the code as much as possible, it would be great.  
I know there will be a lot of changes, it's inevitable, but if it could respect the current coding style it would be great.  

Looking forward for your PR

**Comment by GervinFung** [comment]
Do you mind sharing your current `.prettierrc` config or do you have any particular format in mind?

**Comment by garronej** [comment]
Sure, it would be something like:  

```json
{
    "printWidth": 150,
    "tabWidth": 4,
    "useTabs": false,
    "semi": true,
    "singleQuote": false,
    "quoteProps": "preserve",
    "trailingComma": "none",
    "bracketSpacing": true,
    "arrowParens": "avoid"
}
```

**Comment by josh-hemphill** [comment]
ESLint now provides formatting directives, and for VSCode autoformats through the apis it exposes to comply with any existing ESLint settings when `"eslint.format.enable": true,` is set.
