### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ovesco** [garronej/denoify#5]
Using `exec('rm -rf ...')` directly prevents usage without git bash, and even with it I didn't manage to run denoify on windows. I'm currently working on it, could https://www.npmjs.com/package/rimraf be considered as a good replacement ?

**Comment by garronej** [comment]
So Denoify doesn't run on windows? Bummer.  
I tried to remain OS-agnostic when writing it but I'll admit I haven't it on windows.
Regarding rimraf, why not if what it does can't easily be replicated with the node's builtins....

I will try to boot in windows and see what is up, could you give me a way to reproduce ?

**Comment by ovesco** [comment]
Yes I simply tried to build https://github.com/ovesco/diosaur on Windows with denoify using the powershell

**Comment by garronej** [comment]
I see, I will use `fs.unlinkSync` instead

**Comment by garronej** [comment]
Ok, I am able to reproduce with powershell.
It is working with bit bash for me though.  

Working on resolving the issue

**Comment by garronej** [comment]
@ovesco it should be working in windows using powershell now
