### ISSUE TITLE
Ran up against GitHub api limits quickly

### ISSUE THREAD

**Issue by josh-hemphill** [garronej/denoify#50]
Is there a way to cache and/or disable the automated package resolution?
I was running denoify several times to see where I needed to add some more stuff, and really all I needed when testing was to check the data passing through the custom resolver, the rest had already been resolved.

**Comment by garronej** [comment]
Hi @josh-hemphill, thank you for reaching out.  
You can provide a github access token, it doesn't need to have any particular aces.  
Ref: https://github.com/garronej/denoify/blob/master/README.md#deal-with-github-api-rate-limit-exceeded  

Best regards,

**Comment by jamesarosen** [comment]
This documentation seems to have been removed. Is there an updated version available?

**Comment by garronej** [comment]
Hey @jamesarosen,  

Thank you for pointing this out.  

This section has been moved to the documentation website: https://docs.denoify.land/deal-with-github-api-rate-limit-exceeded
