### ISSUE TITLE
Combined (`default` + `named`) imports not transformed

### ISSUE THREAD

**Issue by josh-hemphill** [garronej/denoify#52]
I've run into imports that try to import both the default and named imports at the same time, and they do not get transformed, resulting in extentionless imports in the deno code.
e.g. (from the Tedious package I'm trying to convert)
```ts
import metadataParse, { Metadata } from '../metadata-parser';
import Parser, { ParserOptions } from './stream-parser';
import { ColMetadataToken } from './token';
```
results in
```ts
import metadataParse, { Metadata } from '../metadata-parser';
import Parser, { ParserOptions } from './stream-parser';
import { ColMetadataToken } from './token.ts';
```

Here's the modifications to the example repo so you can observe: https://github.com/josh-hemphill/my_dummy_npm_and_deno_module

**Comment by garronej** [comment]
I can reproduce

**Comment by garronej** [comment]
Fixed in latest release, thanks for reporting.
