### ISSUE TITLE
Node builtin modules with partial support can't be overridden with replacer or ports options

### ISSUE THREAD

**Issue by josh-hemphill** [garronej/denoify#53]
It looks like I'm getting node modules being replaced with DENOIFY: DEPENDENCY UNMET (BUILTIN), is there a config I'm missing to be able to set those to use the incomplete deno_std compat shims?
The README says these were supported in v0.11, but if I add an import dns from 'dns' to the demo repo with the updated denoify, with or without a manual port/replacement, it always generates import dns from 'dns DENOIFY: DEPENDENCY UNMET (BUILTIN)'.

My last update to my fork of the example repo contains an reproduction of this as well: https://github.com/josh-hemphill/my_dummy_npm_and_deno_module

**Comment by garronej** [comment]
I can reproduce, thanks for reporting, fixing.

**Comment by garronej** [comment]
@josh-hemphill, it's fixed... eventually
