### ISSUE TITLE
feat(config-file): provide support for config file

### ISSUE THREAD

**Issue by GervinFung** [garronej/denoify#55]
Hi sir, I thought that it might be a good idea to provide a config file as an alternative to specify the configs in `package.json`. We can specify `.prettierrc` or `jest.config.js` in addition to specify the configs through package.json. So we can have `.denoify` or `.denoify.js` etc. The main purpose is to not cloud `package.json` with a lot of stuffs

**Comment by garronej** [comment]
I agree

**Comment by GervinFung** [comment]
Yeah, I want to do it. Before that, do you have any file naming convention that you prefer?

**Comment by garronej** [comment]
How about `denoifyrc.json` and `denoifyrc.js`?

**Comment by GervinFung** [comment]
Sure, I also think that if there are 2 configs in `package.json` and in a config file, the one in `package.json` will take higher priority

**Comment by garronej** [comment]
I gave you write access on the repo so you can create a feature branch.  
https://github.com/garronej/denoify/invitations  
I also invited you to the GitBook.  
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/6702424/184091634-d13aa306-cd93-4c6b-bb88-a053ee002ecc.png">

Now could be a good time to start building a proper documentation for the project.

**Comment by garronej** [comment]
Also, just so you know, there is an important item in my TODO list: Improve the ability of Denoify to automatically discover Deno port of a module.  
See the TODO in [this reply](https://github.com/garronej/denoify/issues/35#issuecomment-944506960).

**Comment by garronej** [comment]
I started a refactor of the build options but I'm aborting it for now.  
Documenting the breaking changes and testing to make sure it works on both windows and unix systems would take me to much time that I have avalible on vacations.  
I put it for lated though as I would like to have a single file responsable of parsing the build options and infering the rellevent defaults.  
I also would like to remove the cli compilation options because I would like to be able to quickly see how a repo is using denoify.  
```typescript


import { z } from "zod";
import { assert } from "tsafe/assert";
import type { Equals } from "tsafe";
import { normalize as pathNormalize, relative as pathRelative } from "path";
import { toPosix } from "../../tools/toPosix";
import { isInsideOrIsDir } from "../../tools/isInsideOrIsDir";

type ParsedPackageJson = {
	main?: string;
	denoify?: {
		replacerPath?: string;
		ports?: { [portName: string]: string };
		include?: (string | { srcPath: string; destDirPath: string; destBasename?: string })[];
		outDir?: string;
		srcDir?: string;
		srcIndexTsFilePath?: string;
	};
	dependencies?: { [dependencyName: string]: string };
	devDependencies?: { [dependencyName: string]: string };
};

const zParsedPackageJson = z.object({
	"main": z.string().optional(),
	"denoify": z.object({
		"replacerPath": z.string().optional(),
		"ports": z.record(z.string(), z.string()).optional(),
		"include": z.array(z.union([z.string(), z.object({
			"srcPath": z.string(),
			"destDirPath": z.string(),
			"destBasename": z.string().optional(),
		})])).optional(),
		"outDir": z.string().optional(),
		"srcIndexTsFilePath": z.string().optional(),
		"srcDir": z.string().optional()
	}).optional(),
	"dependencies": z.record(z.string(), z.string()).optional(),
	"devDependencies": z.record(z.string(), z.string()).optional()
});

assert<Equals<ReturnType<typeof zParsedPackageJson["parse"]>, ParsedPackageJson>>();

type ParsedTsConfigJson = {
	compilerOptions?: {
		outDir?: string;
	}
};

const zParsedTsconfigJson = z.object({
	"compilerOptions": z.object({
		"outDir": z.string().optional(),
	}).optional()
});

assert<Equals<ReturnType<typeof zParsedTsconfigJson["parse"]>, ParsedTsConfigJson>>();

export type BuildOptions = {
	replacerPath: string | undefined;
	ports: { [portName: string]: string };
	include?: (string | { srcPath: string; destDirPath: string; destBasename?: string })[];
	outDir: string;
	srcDir: string;
	/** Relative to the src/ dir. Eg: src/lib/index.ts */
	indexRelativePath: string | undefined;
	tsconfigOutDir: string | undefined;
	dependencies: { [dependencyName: string]: string };
	devDependencies: { [dependencyName: string]: string };
};

export function readBuildOptions(
	params: {
		packageJson: string;
		tsconfigJson: string | undefined;
		existingSrcLikeDir: "src" | "lib"
	}
): BuildOptions {

	const { packageJson, tsconfigJson, existingSrcLikeDir } = params;

	const parsedPackageJson = zParsedPackageJson.parse(JSON.parse(packageJson));
	const parsedTsconfigJson = tsconfigJson === undefined ? undefined : zParsedTsconfigJson.parse(JSON.parse(tsconfigJson));

	const toCleanPath = <T extends string | undefined>(path: T): T => path === undefined ? undefined : toPosix(pathNormalize(path)) as any;

	const tsconfigOutDir = toCleanPath(parsedTsconfigJson?.compilerOptions?.outDir);

	const src= toCleanPath(parsedPackageJson.denoify?.src) ?? existingSrcLikeDir;

	return {
		"replacerPath": toCleanPath(parsedPackageJson.denoify?.replacerPath),
		"ports": parsedPackageJson.denoify?.ports ?? {},
		"include": (parsedPackageJson.denoify?.include ?? ["README.md", "LICENSE", "CHANGELOG.md"])
			.map(entry => typeof entry === "string" ? pathNormalize(entry) : {
				"srcPath": toCleanPath(entry.srcPath),
				"destDirPath": toCleanPath(entry.destDirPath),
				"destBasename": entry.destBasename
			}),
		"out": parsedPackageJson.denoify?.outDir ?? (()=>{

			if( tsconfigOutDir === undefined ){
				return undefined;
			}

			return "todo";


		})() ?? "deno_dist",
		src,
		"indexRelativePath":  (() => {

			step: {
				const indexPath = parsedPackageJson.denoify?.index;

				if( indexPath === undefined ){
					break step;
				}

				return pathRelative(src, toCleanPath(indexPath));


			}

			if (tsconfigOutDir === undefined) {
				return;
			}

			const main = toCleanPath(parsedPackageJson.main);

			if( main === undefined ){
				return;
			}

			if (
				!isInsideOrIsDir({
					"dirPath": tsconfigOutDir,
					"fileOrDirPath": main
				})
			) {
				return;
			}

			const indexFileRelativePath = 
				pathRelative(
						tsconfigOutDir,
						main // ./dist/lib/index.js
					) // ./lib/index.js
					.replace(/\.js$/i, ".ts");

			return indexFileRelativePath;


		})(),
		tsconfigOutDir,
		"dependencies": parsedPackageJson.dependencies ?? {},
		"devDependencies": parsedPackageJson.devDependencies ?? {}
	};

}




```

**Comment by GervinFung** [comment]
> Sure, I also think that if there are 2 configs in `package.json` and in a config file, the one in `package.json` will take higher priority

To be clarify doubts, this means that the params in `package.json` will take precedence if the equivalent param in `denoifyrc.json` is undefined.

An example will be if the config in `package.json` is
```js
{
    replacer: undefined,
    out: undefined,
    index: 'src/index.ts',
    includes: 'inclues',
    ports: undefined
  }
```
and the one in `denoifyrc.json` is
```js
{
  replacer: undefined,
  out: 'dist',
  index: 'src/index.ts',
  includes: undefined,
  ports: undefined
}
```
then the final output would be
```js
{
  replacer: undefined,
  out: 'dist',
  index: 'src/index.ts',
  includes: 'includes',
  ports: undefined
}
```
Are you ok with this?

**Comment by KillyMXI** [comment]
There was a package made to make it easier to support various conventional config locations and formats.
Can't remember the name unfortunately.
Would it be of help here or `denoify` demands a hand-crafted solution?

**Comment by garronej** [comment]
@GervinFung: Looks good to me! Sure, I'm garronej#2144 on Discord. I'm on vacation so I'm may be long to answer.  
@KillyMXI: I think it will be nice to have something standard yes, if you remember the name.  

Also @GervinFung, note that since yesterday we also read the `denoify.out` option [here](https://github.com/garronej/denoify/blob/8f8f010a4598aaada31cd0de8a10860a1d77234d/src/lib/resolveNodeModuleToDenoModule/resolveNodeModuleToDenoModule.ts#L397).  

It is for enable denoify to replace:  

```typescript
import { createLexer } from "leac";
```

by

```typescript
import { createLexer } from "https://raw.githubusercontent.com/mxxii/leac/v0.5.2/deno/mod.ts";
```

(module using the `denoify.out` option in package.json:  https://github.com/mxxii/leac/blob/20bc039ee3446f7b13cf3f52737b538fece75094/package.json#L86-L88

**Comment by KillyMXI** [comment]
I think it is https://github.com/davidtheclark/cosmiconfig

**Comment by garronej** [comment]
Hi @GervinFung,  
Just to say, in cas you wheren't aware [Deno is about tu support NPM and Node](https://deno.com/blog/changes%23compatibility-with-node-and-npm) out of the box soon.  

I updated Denoify so that  `import express from "express";` automatically converts into:
`import express from "npm:express@5";` but I think I wont be investing much more time into the project since, starting from now, Denoify will mostly be used as a maketing tool for publishing on [deno.land/x](https://deno.land/x).

**Comment by GervinFung** [comment]
> I think it is https://github.com/davidtheclark/cosmiconfig

Thank you for suggesting this package. Initially I hand-crafted the parser for more customizations as there are only 2 config files - `denoifyrc.json` and `denoifyrs.js`. For example, I can warn the users when they forgot to remove the configs in `package.json` after they moved the configs to a config file.

But it's limiting that way as users cannot use extensionless file or YAML file, and in the end I would end up writing lower level of cosmiconfig package in this repository.

**Comment by GervinFung** [comment]
Since this issue is addressed, thus it can be closed

**Comment by garronej** [comment]
It's my bad, I shouldn't have merged yet.

**Comment by GervinFung** [comment]
This time its really resolved, all the tests has passed
