### ISSUE TITLE
Allow to ignore only one line

### ISSUE THREAD

**Issue by riderx** [garronej/denoify#77]
One of the packages I use, use polyfill for fetch, in Deno this is not necessary.
A perfect solution for that could be
```
// @denoify-line-ignore
import 'isomorphic-fetch';
```
This will make the work of the package more simple than create a Deno entry just to remove polyfill.
I believe that could benefit for more than one package.

The other solution found is to use a [`replacer`](https://github.com/garronej/my_dummy_npm_and_deno_module#step-2-dealing-with-your-dependencies) and make it empty, that look less clean than allow ignoring one line.

**Comment by garronej** [comment]
Good idea

**Comment by Sh4yy** [comment]
[@garronej](https://github.com/garronej), thank you for the swift response. [@riderx](https://github.com/riderx) and I had a long discussion last night about different ways of transpiling [LogSnag's](https://logsnag.com/) [NPM package](https://github.com/LogSnag/logsnag.js) and found Denoify the cleanest setup at the moment.

The only issue right now is dropping the isomorphic-fetch import on [index.ts](https://github.com/LogSnag/logsnag.js/blob/main/src/index.ts), preferably without creating a second entry point for Denoify. 

I currently have a post-processing script that removes lines commented via // @denoify-line-ignore; however, it would be much more concise if this is a part of the transpiler instead.

**Comment by garronej** [comment]
Let's go, it's avalaible in 1.3  

See the doc: https://docs.denoify.land/special-comments#denoify-line-ignore  

Thank you again for the recommendation
