### ISSUE TITLE
 deno package registry api

### ISSUE THREAD

**Issue by buttercubz** [garronej/denoify#8]
Hello, with the new deno registration you can consult data to your api, after they deleted the database.json file our tool([trex](https://github.com/crewdevio/Trex)) broke. i think this information can help mend denoify.

`You can query the API as follows`

- https://api.deno.land/modules
> this returns a json with the information of the first 20 packets

- https://api.deno.land/modules?limit=100
> with a limit we can change the number of packages sent to us with a maximum of 100 packages

- https://api.deno.land/modules?limit=100&query=trex
> using query we can specify the name of the package and this will return the list of packages that match the name

You can also use the page parameter to specify the page, default is 1

I hope this information is helpful 🙂

**Comment by garronej** [comment]
It helps a great deal, thank you!

**Comment by qballer** [comment]
Are there docs open source docs for this?

**Comment by garronej** [comment]
Hi @qballer!
Not that I know off beside: https://github.com/denoland/deno_registry2/blob/main/API.md

**Comment by garronej** [comment]
@qballer You can also check [this](https://github.com/denoland/deno_registry2/issues/40#issuecomment-668774286) out, very useful.
